Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -1,6 +1,7 @@
-# This is a basic workflow to help you get started with Actions
-
 name: test CI
+
+env:  
+  TEST_SECRET: ${{ TEST_SECRET }}
 
 # Controls when the workflow will run
 on:
@@ -30,7 +31,29 @@ jobs:
         run: echo Hello, world!
 
       # Runs a set of commands using the runners shell
-      - name: Run a multi-line script
+      - name: Run a multi-line script 2
         run: |
           echo Add other actions to build,
           echo test, and deploy your project.
+
+      - name: Create text file
+        run: echo "Test secret:${MAPS_API_KEY}" >> testf/test.txt
+ 
+      - name: Run a one-line script 3
+        run: echo Hello, world!3
+
+      - name: Search problems-report
+        if: always ()
+        run: |
+         echo "Current path: $PWD"
+         echo "We are looking for the file"
+         find . -name test.txt || echo "File not found"
+
+      - name: Save blackduck-problems-report file
+        if: always ()
+        uses: actions/upload-artifact@v4
+        with:
+           name: test
+           path: testf/test.txt
+      
+
